site_name: SIG Multicluster
repo_url: https://github.com/kubernetes-sigs/sig-multicluster-site
repo_name: kubernetes-sigs/sig-multicluster-site
site_dir: site
docs_dir: site-src
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/k8s-favicon.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
edit_uri: edit/main/site-src/
plugins:
  - search
  - awesome-pages
  - redirects:
      redirect_maps:
        'guides/getting-started.md': 'guides/index.md'
        'contributing/community.md': 'contributing/index.md'
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - toc:
      permalink: true
nav:
  - Overview:
    - Introduction: index.md
    - About API Overview: concepts/about-api.md
    - Multicluster Services API Overview: concepts/multicluster-services-api.md
    - Work API Overview: concepts/work-api.md
    - ClusterProfile API Overview: concepts/cluster-profile-api.md
  - Guides:
    - Index: guides/index.md
    - Implementation Guidelines: guides/guidelines.md
  - Reference:
    - Namespace Sameness: concepts/namespace-sameness.md
    - ClusterSet: api-types/cluster-set.md
    - ServiceExport: api-types/service-export.md
    - ServiceImport: api-types/service-import.md
    - API specification: references/spec.md
  - Contributing:
    - How to Get Involved: contributing/index.md
    - FAQ: contributing/faq.md
  - Announcements:
    - Index: blog/index.md
    - 2022:
      - Archiving Kubefed on Jan 3rd, 2023: blog/2022/2022-11-16_archiving-kubefed-on-Jan-3-2023.md
